<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;

Route::get('/', fn () => redirect(auth()->check() ? '/dashboard' : '/login'));

// Only reachable when FILESYSTEM_DISK=local (see AppServiceProvider's
// buildTemporaryUrlsUsing()) — serves an evidence photo for a signed,
// time-limited link generated by Storage::temporaryUrl(). The signature
// alone gates access, mirroring S3's presigned-URL trust model 1:1
// (nothing here is a new, weaker check than what S3 already provided).
Route::get('evidence-photos/{path}', function (Request $request, string $path) {
    abort_unless($request->hasValidSignature(), 403);

    $disk = Storage::disk('local');
    abort_unless($disk->exists($path), 404);

    return $disk->response($path);
})->where('path', '.*')->name('evidence-photos.show');
